### ISSUE TITLE
Add yarn lockfile

### ISSUE THREAD

**Issue by domoritz** [type-schema/json-schema#1]
It would be good to fix the dependencies to make sure people have reproducible environments.

**Comment by nonara** [comment]
Thanks for the suggestion!

Seems there are two schools of thought on this. I've dug in a bit further to get the full scope. The comments here is a good thread on it: https://dev.to/gajus/stop-using-package-lock-json-or-yarn-lock-3ddi

All in all, I think I may agree that it would be good to commit the lockfile, even though this (and the other packages) will/can be consumed in a library capacity.

Consensus seems to be that generating both yarn.lock and package-lock.json "almost always results in different dependencies". However, it looks like yarn [can use package-lock.json](https://classic.yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/) (as of 2018), so considering that it's built with npm, it should be sufficient to commit package-lock.json.

Any added thoughts or input from your experience, or does that sound good?

**Comment by domoritz** [comment]
I'm very strongly in favor of lockfiles ;-) It doesn't really matter whether you have a lockfile for a library since consumers are not going to use the lockfile. I can tell you from years of experience that lockfiles are the right approach (plus, it's the official recommendation by npm and used by rust, python, and many others now).

**Comment by domoritz** [comment]
I prefer using yarn lockfiles because yarn has been so much better than npm but that's a personal preference.

**Comment by nonara** [comment]
Well, turns out you're getting your wish! 

I used yarn way back when, but after npm finally got working links (or so I thought), I switched back, preferring to stay with the widest used, 'official' tool.

I've been splitting some code into packages and using link, today, and npm is a mess. Every time I register a link and link it in another package, it breaks the link source's dependencies, including TSC. Tried with yarn, and it works fine. 

That aside, speed and UI are a major improvement! Yarn it is!

**Comment by domoritz** [comment]
Your experience reflects my experience.

**Comment by nonara** [comment]
What's your opinion on using a mono-repo in this case?

![image](https://user-images.githubusercontent.com/1427565/80170860-f342ba00-85b6-11ea-9141-1597c59cf3e3.png)

If we go that route, I'll keep `json-schema` as a separate repo. Benefits would be root ts-config base, easier integration testing, etc.

Thoughts?

**EDIT:** Giving it more thought, I'm convinced that this is the route to go, but I'm open to discussion if you have any objections.

**Comment by domoritz** [comment]
I like monorepos. We use it (with lerna) for https://github.com/vega/vega. It allows you to easily share babel, prettier, eslint, jest, etc configs.

**Comment by nonara** [comment]
@domoritz Facing an issue with yarn. I use `ts-patch` to modify typescript to support transformers. The problem is, yarn restores from cache every time `yarn add` or `yarn remove` are run.

I can mitigate `yarn add` by using a `prepare` script, which is fine, but it isn't invoked after remove.

Would you happen to know of a way I can:
- Override the cache restoration behaviour (selectively for TS or project-wide)
- Trigger a script after remove

**EDIT**
I don't love it, but I've manually configured a cache path, and I'm patching the cache version as well. Perfectly fine for this purpose, but it does leave me concerned for `ts-patch` users who use yarn.

**Comment by domoritz** [comment]
I never had to patch dependencies.
